### ISSUE TITLE
The permissions of the samba_shares_root should be independent of share permissions

### ISSUE THREAD

**Issue by bertvv** [bertvv/ansible-role-samba#3]
The permissions of samba_shares_root should be set separately. Now, it will take the permissions of the first share being created. If that happens to be a restricted one (e.g. with directory mode 0700), shares are not visible for other users.

**Comment by birgitcroux** [comment]
I noticed this issue while using this role. I had the opposite problem: I gave control over the shared folders to pretty much any local user with some form of remote access.
Created a pull request before checking the issues here, sorry about that (as you know, I'm pretty new to all this).

**Comment by bertvv** [comment]
Perfect, thanks!
