### ISSUE TITLE
use "map to guest = never"

### ISSUE THREAD

**Issue by debuglevel** [bertvv/ansible-role-samba#41]
Please use `map to guest = never` as default (which is the Samba default according to the man page).

If you use `map to guest = bad user`, one will be asked for credentials when browsing available samba shares from a Windows client. Windows will save those credentials, because they apparently worked (but were actually wrong). The Windows client will never be asked again for those credentials on browsing shares.

For me, it also broke somehow the authentication for a share (although the Windows GUI asked again for a password) because something seems to mess up in the authentication process then.

**Comment by bertvv** [comment]
Fixed in v2.7.1! Thanks for reporting this and sorry for the delay.
