### ISSUE TITLE
Note that samba_mitigate_cve_2017_7494 disables share browsing

### ISSUE THREAD

**Issue by debuglevel** [bertvv/ansible-role-samba#42]
`samba_mitigate_cve_2017_7494`, which sets `nt pipe support = no` prevents access to `IPC$`. Therefore, Windows clients cannot browse shares anymore. README should state this behaviour.

The best option might be to ignore `samba_mitigate_cve_2017_7494` on patched Samba versions.

**Comment by bertvv** [comment]
Fixed in v2.7.1. Thanks for reporting this. I followed your suggestion: the workaround is now only applied on potentially vulnerable versions of Samba.
