### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by vladgh** [bertvv/ansible-role-samba#71]
Is this role still maintained?

**Comment by aairey** [comment]
@bertvv

**Comment by bertvv** [comment]
Unfortunately, I do not have enough time to keep up with issues and pull requests. If anyone is interested to become a maintainer, please let me know.

**Comment by vladgh** [comment]
I would be interested.

**Comment by bertvv** [comment]
After discussion with @vladgh, I have decided to hand over maintenance to him. He created a fork that can be found [here](https://github.com/vladgh/ansible-collection-vladgh-samba), the Ansible galaxy page for this role is [here](https://galaxy.ansible.com/vladgh/samba).
